server:
  port: 8830

eureka:
  instance:
#    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
#    status-page-url-path: /management/info
#    health-check-url-path: /management/health
#    metadata-map:
#      management.context-path: /management
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8800/eureka/
    register-with-eureka: true
    fetch-registry: false


management:
  security:
    enabled: false
  context-path: /management
